# Generated by Django 4.1.2 on 2022-10-17 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamsname', models.CharField(max_length=100)),
                ('teamsimg', models.ImageField(upload_to='photos')),
                ('teamsdesc', models.TextField()),
            ],
        ),
    ]
